name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: run test
        run: go test -v ./...